# name: Flake

# # Builds and tests the flake using Nix on Linux and macOS.

# on:
#   - push
#   # - pull_request

# defaults:
#   run:
#     shell: bash

# jobs:
#   flake:
#     name: flake - ${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [ubuntu-latest, macos-latest]

#     steps:
#       - name: Clone the source
#         uses: actions/checkout@v3

#       - name: Install Nix
#         uses: cachix/install-nix-action@v20
#         with:
#           nix_path: nixpkgs=./nix/nixpkgs.nix

#       - name: Install Cachix
#         uses: cachix/cachix-action@v12
#         with:
#           name: tweag-haskellr
#           authToken: ${{ secrets.CACHIX_TWEAG_HASKELLR_AUTH_TOKEN }}
#           cachixArgs: --compression-method zstd --compression-level 16

#       - name: Build inline-r
#         run: nix build -L .#inline-r --verbose

#       - name: Build H
#         run: nix build -L .#H --verbose

#       - name: Build IHaskell
#         run: nix build -L .#IHaskell --verbose

#       - name: Build HaskellR-examples
#         run: nix build -L .#HaskellR-examples --verbose
